### ISSUE TITLE
Incorrect link to repository - the name has changed

### ISSUE THREAD

**Issue by gibbardsteve** [ONS-Innovation/github-api-package#12]
https://github.com/ONS-Innovation/github-api-package/blob/d9d1cf493add9b3093d947385da4d6a6c0e2365e/setup.py#L7

There are also some incorrect examples in the top-level README and mkdocs documentation.

**Comment by TotalDwarf03** [comment]
fixed in documentation PR

https://github.com/ONS-Innovation/github-api-package/pull/14
